version: "3.8"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - ${MASTER_DB_PORT}:${MASTER_DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${MASTER_DB_USER}
      - MYSQL_PASSWORD=${MASTER_DB_PASSWORD}
      - MYSQL_DATABASE=${MASTER_DB_NAME}
      - MYSQL_TCP_PORT=${MASTER_DB_PORT}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mysql_db
    links:
      - mysql_db:mysql_db
    restart: on-failure
    volumes:
      - ./data/upload:/root/public

  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}
    depends_on:
      - server
    restart: on-failure

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - website
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
