version: "3.8"

services:
  mysql_db:
    container_name: dev_mysql_db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${MASTER_DB_USER}
      - MYSQL_PASSWORD=${MASTER_DB_PASSWORD}
      - MYSQL_DATABASE=${MASTER_DB_NAME}
    volumes:
      - dev_mysql_data:/var/lib/mysql
    restart: always

  server:
    container_name: dev_go_server
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mysql_db
    links:
      - mysql_db:mysql_db
    volumes:
      - .:/app
    restart: always

volumes:
  dev_mysql_data:
